export const FORMULARIO_PROYECTO = "FORMULARIO_PROYECTO";
export const OBTENER_PROYECTO = "OBTENER_PROYECTO";
export const AGREGAR_PROYECTO = "AGREGAR_PROYECTO";
export const VALIDAR_PROYECTO = "VALIDAR_PROYECTO";
export const SELECCIONAR_PROYECTO = "SELECCIONAR_PROYECTO";
export const ELIMINAR_PROYECTO = "ELIMINAR_PROYECTO";
export const ERROR_PROYECTO = "ERROR_PROYECTO";

export const OBTENER_TAREA = "OBTENER_TAREA";
export const AGREGAR_TAREA = "AGREGAR_TAREA";
export const VALIDAR_TAREA = "VALIDAR_TAREA";
export const ELIMINAR_TAREA = "ELIMINAR_TAREA";
export const ACTUAL_TAREA = "ACTUAL_TAREA";
export const EDITAR_TAREA = "EDITAR_TAREA";

export const MOSTRAR_ALERTAS = "MOSTRAR_ALERTAS";
export const OCULTAR_ALERTAS = "OCULTAR_ALERTAS";

export const REGISTRO_EXITOSO = "REGISTRO_EXITOSO";
export const REGISTRO_ERROR = "REGISTRO_ERROR";
export const OBTENER_USUARIO = "OBTENER_USUARIO";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CERRAR_SESION = "CERRAR_SESION";
